### ISSUE TITLE
Error downloading the data

### ISSUE THREAD

**Issue by manmeet3591** [scotthosking/get-station-data#7]
Everything was running fine until yesterday, but suddenly it has stopped working. I use the library in google colab and install it every time by cloning from github.

Downloading station data...
  0%|          | 0/1 [00:00<?, ?it/s]
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/content/get_station_data/ghcnd.py", line 76, in process_stn
    start_year = int(date_range[0][:4])
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-8-e63f87ef99fd> in <cell line: 1>()
      1 if download_data:
----> 2     df_ = ghcnd.get_data(my_stns.iloc[[0]])
      3     df_

7 frames
/content/get_station_data/ghcnd.py in process_stn()
     74     # if the requested range and the stations range as provided in the metadata don't overlap
     75     # return and empty df and don't download/read file
---> 76     start_year = int(date_range[0][:4])
     77     end_year = int(date_range[0][:4])
     78     if date_range:

TypeError: 'NoneType' object is not subscriptable

**Comment by scotthosking** [comment]
@magnusross - do you happen to see what is happening here following the PR?

**Comment by magnusross** [comment]
Hi @manmeet3591 

I’m really sorry about this, I have recently been doing some work to try and speed up the package but seem to have introduced a bug in the process. This is my fault and should have been caught in testing, again I apologise for this and the inconvenience for you. 

Unfortunately I am currently away from my computer and will be until later this evening. In order to get it back to working order, the best way might be to to clone the code and then checkout the commit that has the code before the new changes. The commit ID for that code is b835b6334f, so after cloning, if you run `git checkout b835b6334f .` that should give you the correct code. Alternatively,
if you specify a date range for the station data you wish to request then that also should work, you can do this by including something like `date_range=(“1950-01-01”, “2023-01-01”)`

I can see what the bug is, but am not confident in fixing it from my phone as I won’t be able to test, but I will fix it tonight/early tomorrow morning and update the code. 

Again apologies for this @manmeet3591 , and to you @scotthosking  for the headache!

**Comment by magnusross** [comment]
Hi @manmeet3591 

I've fixed the error and merged it now, so hopefully you code should be back to working as usual. Again sorry for the inconvenience with this. 

One other thing to be aware of, in the previous update the three columns that were previously "year", "month", "day"  have now been merged into a single date time column "date".  I hope this doesn't cause issues from you. 

Please let me know if you have any more problems, I will close in a few days if I don't hear anything.

 Thanks.

**Comment by manmeet3591** [comment]
Thank you so much.
